services:
  bio1apache:
    build: 
      context: .
      dockerfile: docker/bio1-apache.Dockerfile
    ports:
      - "80:80"
      - "443:443"
  # bio1server:
  #   build: 
  #     context: .
  #     dockerfile: docker/bio1-server.Dockerfile
  #     args:
  #       - EXTERNAL_API=127.0.0.1