services:
  bioapache:
    container_name: ${APP_NAME}-apache
    build: 
      context: .
      dockerfile: docker/apache.Dockerfile
      args:
        - DNAS_SRC=${DNAS_SRC}
        - DNAS_DEST=${DNAS_DEST}
        - FPM_HOST=${FPM_HOST}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - biomysql
    networks:
      - bio

  bioserver:
    container_name: ${APP_NAME}-server
    build: 
      context: .
      dockerfile: docker/server.Dockerfile
      args:
        - SERVER_PATH=${GAME_SERVER_PATH}
        - RUN_FILE_PATH=${GAME_RUN_FILE_PATH}
    ports:
      - "${LOBBY_SERVER_PATH}:${LOBBY_SERVER_PATH}"
      - "${GAME_SERVER_PORT}:${GAME_SERVER_PORT}"
    depends_on:
      - biomysql
    networks:
      - bio

  biofpm:
    container_name: ${APP_NAME}-fpm
    build: 
      context: .
      dockerfile: docker/fpm.Dockerfile
      args:
        - DNAS_SRC=${DNAS_SRC}
        - DNAS_DEST=${DNAS_DEST}
    depends_on:
      - biomysql
      - bioserver
    networks:
      - bio

  biomysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_HOST}
    networks:
      - bio
    volumes:
      - ${GAME_SERVER_PATH}/database/bioserver.sql:/docker-entrypoint-initdb.d/bioserver.sql:rw
      - ./dbdata:/var/lib/mysql

networks:
  bio:
    driver: bridge
    name: ${APP_NAME}-network