services:
  bio1apache:
    build: 
      context: .
      dockerfile: docker/bio1-apache.Dockerfile
      args:
        - HOST_IP=10.0.0.200
    ports:
      - "80:80"
      - "443:443"
      # - "53:53/tcp"
      # - "53:53/udp"
  # bio1server:
  #   build: 
  #     context: .
  #     dockerfile: docker/bio1-server.Dockerfile
  #     args:
  #       - EXTERNAL_API=127.0.0.1